collectform/collectform/urls.py
from django.contrib import admin
from django.urls import path

from formapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # * CREATE
    path('create/', views.Create.as_view(), name="create"),

    # * READ
    path('', views.Read.as_view(), name="read"),

    # * UPDATE
    path('update/<int:pk>/', views.Update.as_view(), name="update"),

    # * DELETE
    path('delete/<int:pk>/', views.Delete.as_view(), name="delete")
]

collectform/formapp/models.py
from django.db import models

# Create your models here.

# * Foreignkey was not used.
GENDER  = (
    ('M', 'M'),
    ('F', 'F')
)


CLASS  = (
     ('JSS 1', 'JSS 1'),
     ('JSS 2', 'JSS 2'),
     ('JSS 3', 'JSS 3'),
     ('SSS 1', 'SSS 1'),
     ('SSS 2', 'SSS 2'),
     ('SSS 3', 'SSS 3')
)


class Candidate(models.Model):
    name                = models.CharField(max_length=80)
    phone               = models.CharField(max_length=30)
    email               = models.CharField(max_length=120)
    gender              = models.CharField(max_length=1,null=True, choices=GENDER)
    student_class        = models.CharField(max_length=80, null=True, choices=CLASS)
    
    
    
    def __str__(self):
        return self.name

collectform/formapp/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from formapp.models import Candidate

class CandidateForm(forms.ModelForm):
    class Meta:
        models = Candidate
        fields = "__all__"

collectform/formapp/views.py
from django.shortcuts import render

# Create your views here.
from formapp.models import Candidate
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# * (C) CREATE
class Create(CreateView):
    model = Candidate
    fields = '__all__'
    success_url  = reverse_lazy('read')


# * (R) READ
class Read(ListView):
    model = Candidate
    queryset = Candidate.objects.all()



# * (U) UPDATE
class Update(UpdateView):
    model = Candidate
    fields  = '__all__'
    success_url = reverse_lazy('read')
    


# * (D) DELETE
class Delete(DeleteView):
     queryset = Candidate.objects.all()
     success_url = reverse_lazy('read')
    

collectform/formapp/templates/formapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- *  BOOTSTRAP 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- * FontAweSome link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <!-- * Favicon -->
    <link  href={% static "img/favicon.ico" %}  rel="shortcut icon"  >


    <!-- * Logo -->
    <link  href={% static "img/logo.ico" %}  rel="shortcut icon"  >


            <!-- *  -->
    <link  href={% static "style/favicon.css" %}  rel="stylesheet>

    <title>Document</title>
</head>
<body>


<div class="wrapper">
        <!-- * NAVBAR -->

        <header>
            <nav class="navbar navbar-expand-lg navbar-dark navbar {% block navbar %}  {% endblock navbar %}">
                <a class="navbar-brand flex-grow-1 text-center">
                    {% block nav-content %}
                        <i class="fas fa-user-friends"></i>&nbsp;&nbsp; LIST OF CANDIDATES
                    {% endblock nav-content %}
                </a>
            </nav>
        </header>







{% block content %}

{% endblock content %}


</div>

<footer class="bg-dark text-center text-lg-start" id="footer" style="color: #fff;">
    <div class="text-center p-3 " style="background-color: rgba(0, 0, 0, 0.2);">
        &copy; {% now "Y" %} Copyright
        <a class="text-light" style="text-decoration: none;">
            <span {% block footer %} style="color: #89cff0;"  {% endblock footer %}>www.astro.com
            </span>
        </a>
    </div>

</footer>




<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    
</body>
</html>

collectform/formapp/templates/formapp/candidate_confirm_delete.html
{% extends "formapp/candidate_list.html" %}

{% comment %} * Navbar background-color  {% endcomment %}

{% block navbar %}
bg-danger
{% endblock navbar %}


{% comment %} * Navbar content {% endcomment %}

{% block nav-content %}
<i class="fas fa-user-times"></i>&nbsp;&nbsp;DELETE CANDIDATE
{% endblock nav-content %}



{% comment %} * FOOTER {% endcomment %}
{% block footer %}

style="color: #ff7f7f;"

{% endblock footer %}

{% comment %} * PAGE CONTENT {% endcomment %}
{% block content %}
<br>
<div class="container mt-5" style="width: 450px;">

    <div class="card p-3 border-dark">
        <h6 class="modal-title">
            <i class="fas fa-trash-alt"></i>&nbsp;&nbsp; Delete Candidate
        </h6>
        <hr>
        <div class="text-center text-danger">
            <i class="far fa-times-circle fa-5x mb-4 mt-2"></i>
        </div>
        <div class="text-center text-danger">
            <span>
                DO YOU WANT TO DELETE THIS CANDIDATE ???
            </span>
            <div class="text-dark mt-3 mb-2">Candidate: <strong>{{ candidate.name }}</strong></div>
        </div>

        <hr>
        <form method="POST">
            {% csrf_token %}

            <input type="submit" value="Delete" style="float: right; " class="btn btn-outline-danger btn-sm ms-2">
            <a href="{% url 'read' %}" class="btn btn-secondary btn-sm" style="float: right;">Cancel</a>
        </form>
    </div>

    <br><hr><br>
    <h6 class="text-danger">If you proceed, this data will become unrecoverrable.</h6>
</div>

{% endblock content %}

collectform/formapp/templates/formapp/candidate_form.html
{% extends "formapp/candidate_list.html" %}

{% comment %} * Crispy Form Tag {% endcomment %}

{% load crispy_forms_tags %}
{% comment %} * NavBar Content {% endcomment %}

{% block nav-content %}
<i class="fas fa-user-check"></i>&nbsp;&nbsp; CANDIDATE
{% endblock nav-content %}

<!-- * Page content -->


{% block content %}

<div class="container mt-5" style="width: 450px">
    <div class="card p-3 border-dark">
        <form action="" autocomplete="off" method="POST">
            {% csrf_token %}
            {{ form.name|as_crispy_field }}
            {{ form.phone|as_crispy_field }}
            {{ form.email|as_crispy_field }}
            {{ form.gender|as_crispy_field }}
            {{ form.student_class|as_crispy_field }}
                <br>
                <hr>
                <div class="d-grid gap-2 mb-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{% url 'read' %}" class="btn btn-secondary">Cancel</a>
                </div>

                <hr>
        </form>
    </div>

</div>
  
{% endblock content %}

collectform/formapp/templates/formapp/candidate_list.html
{% extends "formapp/base.html" %} {% block content %}

<div class="container">
  <a href="{% url 'create' %}" class="btn btn-outline-primary mb-3 mt-5">
    <i class="fas fa-plus"></i>&nbsp;&nbsp; Candidate
  </a>
  <table
    class="table table-bordered"
    style="text-align: center; font-size: 16px"
  >
    <thead class="table-primary">
      <tr>
        <th style="width: 25%">Name</th>
        <th style="width: 20%">Phone</th>
        <th style="width: 23%">Email</th>
        <th style="width: 7%">Gender</th>
        <th style="width: 15%">Class</th>
        <th colspan="2" style="width: 10%">Actions</th>
      </tr>
    </thead>

    <!-- * Data from the database -->
    {% for candidate in object_list %}
    <tr>
      <td>{{ candidate.name }}</td>
      <td>{{ candidate.phone }}</td>
      <td>{{ candidate.email }}</td>
      <td>{{ candidate.gender }}</td>
      <td>{{ candidate.student_class }}</td>
      <td>
        <a
          href="{% url 'update' pk=candidate.id %}"
          class="btn btn-primary btn-sm"
          style="width: 45px"
        >
          <i class="fas fa-pen"></i>
        </a>
      </td>
      <td>
        <a
          href="{% url 'delete' pk=candidate.id %}"
          class="btn btn-secondary btn-sm"
          style="width: 45px"
        >
          <i class="fas fa-trash-alt"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

{% endblock content %}